<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigitalSignature.Domain\DigitalSignature.Domain.csproj" />
    <ProjectReference Include="..\DigitalSignature.Application\DigitalSignature.Application.csproj" />
    <ProjectReference Include="..\DigitalSignature.Infrastructure\DigitalSignature.Infrastructure.csproj" />
  </ItemGroup>

</Project>
